#!/usr/bin/env ruby
# Usage: quick ssh <name> [<options>]
# Summary: Allows for quick ssh into a given name
# Help: SSHs into the host provided, if that host exists in quicks yaml files.
# 
# To Add a host:
#   quick ssh host -h hostname -u username -p 22
#
#   -h
#
#     The hostname/IP of the server you want to connect to.
#
#   -u (optional)
#
#     The Username you want to connect as.
#
#   -p (optional)
#
#     The port you want to connect over
#
# To list your hosts:
#   quick ssh -l
#
# To Install you ssh Key
#
#   quick ssh host -i
#
#   This installs your SSH key for passwordless login
#     BE CAREFUL USING THIS, IF YOUR COMPUTER IS COMPRAMISED 
#     ANYONE WILL BE ABLE TO ACCESS YOUR SERVERS
#     SEE: http://www.debian-administration.org/articles/530

require './lib/quick'

Quick::SSH.new(ARGV)